services:
  gzctf-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gzctf-discord-bot
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Docker volume for persistent data and logs
    volumes:
      - gzctf-bot-volume:/app
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "2G"
        max-file: "10"

# Named volume
volumes:
  gzctf-bot-volume:
    driver: local

networks:
  default:
    driver: bridge